### ISSUE TITLE
Deploy not possible

### ISSUE THREAD

**Issue by jolau** [caprica/vlcj-player#1]
The current version can't be deployed with maven, because it is pointing to the vlcj version 3.3, which isn't published yet.

**Comment by caprica** [comment]
To be honest, I expect people who are interested in vlcj-player to have both vlcj and vlcj-player open as projects in their IDE, and then the transient snapshot dependency on vlcj doesn't matter. If you do this, the vlcj snapshot will end up in your local maven repo too.

The idea of vlcj-player is to be an example/tutorial/reference implementation for how to use vlcj.

Anyway, this will be resolved in time, but by it's very nature as an example/tutorial project the vlcj-pro project is likely to always track the latest vlcj project, and from time to time that will mean a transient snapshot dependency on vlcj.

**Comment by jolau** [comment]
Ok, also true. But anyway would be really convenient if you could release from time to time a running jar. Good to quickly try it out and figuring out if it is worth for further investigations.

**Comment by caprica** [comment]
Yes, it will indeed be 'properly' released from time to time with a non-snapshot dependency, your timing is just a bit unlucky at the moment.

**Comment by jolau** [comment]
Haha, ok, no problem. Thanks for the fast response!

**Comment by caprica** [comment]
Updated to use vlcj 3.3.0 release. It takes a little while to propagate to Maven Central, but this issue can be resolved now.
