### ISSUE TITLE
can not run in max os

### ISSUE THREAD

**Issue by bewithme** [caprica/vlcj-player#13]
what's wrong with my player?

vlcj             : 4.0.7
os               : Mac OS X 10.12.6 x86_64
java             : 1.8.0_45 Oracle Corporation
java.home        : /Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/jre
jna.library.path : <not set>
java.library.path: /Users/xxxx/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
PATH             : /usr/bin:/bin:/usr/sbin:/sbin
VLC_PLUGIN_PATH  : /disks/data/build/install/libs-3/plugins
DYLD_LIBRARY_PATH          : <not set>
DYLD_FALLBACK_LIBRARY_PATH : <not set>
Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'vlc':
dlopen(libvlc.dylib, 9): image not found
dlopen(libvlc.dylib, 9): image not found
Native library (darwin/libvlc.dylib) not found in resource path

**Comment by caprica** [comment]
It looks like VLC_PLUGIN_PATH is hard-coded for my PC. I do that from time-to-time when I'm testing with a newer dev snapshot of VLC. I have fixed that.

Please try again.

As part of the vlcj 4.0.0 release I thoroughly tested native discovery on every platform and it should just work if you have VLC installed the "official" way.

**Comment by caprica** [comment]
However, you should know that vlcj-player will not work properly on OSX due to OSX not having any heavyweight AWT.

You need to look at CallbackVideoSurface or CallbackMediaPlayerComponent on OSX.

This has been discussed at length in various issues at the vlcj project page at Github.

**Comment by bewithme** [comment]
thank you so much

发自我的 iPhone
