### ISSUE TITLE
how to play rtsp stream with this player

### ISSUE THREAD

**Issue by bewithme** [caprica/vlcj-player#14]
how to play rtsp stream like rtsp://user:password@xxx.xxx.xxx.xxx:554/h264/ch1/main/av_stream with this player ?

**Comment by caprica** [comment]
You need to be aware this project is a *demo* of how to integrate most, but not all, vlcj features.

It is *not* a full-blown fully-featured application and is instead supposed to be used only as an example or something to help you learn how to use vlcj.

So, in short, you can't use this particular project to play an RTSP stream. You are of course free to change the source yourself to do that.

Anyway, if you create your own application you should just be able to do this:

```
mediaPlayer().media().play("rtsp://user:password@xxx.xxx.xxx.xxx:554/h264/ch1/main/av_stream");
```
