### ISSUE TITLE
Unable to change the audio output device

### ISSUE THREAD

**Issue by aiscy** [caprica/vlcj-player#16]
First of all, I would like to thank you for maintaining this beautiful library! Everything was fine until the moment I need to change the audio output device. It looks very simple, but I didn't manage to get it to work, so I decided to have a look at the implementation in vlcj-player, but here again I failed. No matter what device I choose, it still use the default one. The only solution I found was to start the playback, pause it, change the output device and then resume the playback, but it only works once.
![Version](https://i.imgur.com/jNHbuqE.png)
I tried different versions of vlcj, from 4.0.5 to 4.2.0, but it makes no difference.
Also, I made a little video in order to not be unfounded :)
https://vimeo.com/375696625
I'd like to provide any additional information if needed.

vlcj             : 4.2.0
os               : Windows 10 10.0 amd64
java             : 1.8.0_222 AdoptOpenJDK

**Comment by caprica** [comment]
I just tested vlcj-player.
The menu shows two audio devices.
I can swap between one and the other, while playback is ongoing.

So I don't know what else I can tell you.

Maybe there's problem on Windows, I don't know. (I use Linux for my development and testing).

Maybe enable VLC verbose logging and check the native logs when you change audio device.

Also, if you start the VLC application, can you change audio device there?
![Screenshot from 2019-11-26 17-33-32](https://user-images.githubusercontent.com/1385879/69657994-413cab80-1073-11ea-9b8c-818ff2cb758b.png)

**Comment by aiscy** [comment]
> Also, if you start the VLC application, can you change audio device there?

Yes, I checked this before creating the issue.

> Maybe there's problem on Windows

Seems like it :(

**Comment by aiscy** [comment]
Welp, I'd like to thank you for your time, but that's just me being a potato.

**Comment by caprica** [comment]
If it works in VLC on Windows, there should be no reason for it not to work via LibVLC/vlcj.

**Comment by caprica** [comment]
Ah, that sounds like a funny story waiting to be told... :-D
