### ISSUE TITLE
missing artifact

### ISSUE THREAD

**Issue by teras** [caprica/vlcj-player#18]
Hello
When trying to compile with maven, I receive a message about missing artifact uk.co.caprica:vlcj:jar:4.0.7-SNAPSHOT

Of course, removing the `-SNAPSHOT` part, fixes the problem.
Maybe this should be the default?
(I am willing to have a pull request if you accept it).

**Comment by caprica** [comment]
Thanks for the report.

The vlcj-player project does need to be brought up to date, the latest vlcj version is now 4.4.2.

It doesn't *really* matter, I expect most people will just pull that project into their IDE and use whatever version of vlcj they want.

But yes, it should be cleaned up and I'll update it myself some time soon.

**Comment by caprica** [comment]
Just checking my local code and I already had a pending change waiting to be pushed for this.

I did not push it yet because it bumps the project to Java 11.

**Comment by teras** [comment]
My humble opinion is, you don't have to update the version, just get off the -SNAPSHOT train.

**Comment by caprica** [comment]
Resolved at b9c5d14fe7222a0523726d42262094f378e997ef.
