### ISSUE TITLE
.

### ISSUE THREAD

**Issue by graysuit** [caprica/vlcj-player#19]

**Comment by caprica** [comment]
The screenshot for this project is a Linux desktop application, but it also works on macOS and Windows.

For Android, I have had reports that vlcj does work on Android, as long as JNA works on Android.

But I do not do any work/testing on Android, so I can't be sure about this.

There is documentation or examples showing how to use vlcj to make something for Android.

There are ways to use LibVLC on Android without vlcj, but again, I can't be sure about this.

**Comment by graysuit** [comment]
Thanks sir,
Where do i get documentation for android libvlc player,
I am new to android studio,
And i get bored of XML errors.

**Comment by caprica** [comment]
I have no idea, that's nothing to do with this project. Try Google!
