### ISSUE TITLE
Not adjusting Video Effects

### ISSUE THREAD

**Issue by sense42** [caprica/vlcj-player#20]
I am trying to adjust the video Brightness / contrast etc. but the vlcj Player does not change the visible video. 
I am using mp4 (converted from h264) video.  I also tried other sample Videos from the internet but had no success. 

Edit: vlc Version 3.0.10

**Comment by caprica** [comment]
Indeed it is not working for me at the moment. I don't know why, it worked when I implemented it.

I have seen a regression in VLC before that temporarily broke this, but in this case I don't know if that happened.

I checked the vlcj 5.0.0-SNAPSHOT code with the TestPlayer from the vlcj-examples project, and with the 4.0.0-git of VLC it did work.

So right now, hmm.....

**Comment by caprica** [comment]
Nothing to fix in vlcj here.
