### ISSUE TITLE
Some problem with fullscreen

### ISSUE THREAD

**Issue by ilia-ru** [caprica/vlcj-player#21]
Good day!

Sorry for my english! :)

I made javafx application and use VCLJ. My application worked good. But Can I ask a question?
I need swith to fullscreen.
I read documentation, and see:
mediaPlayer.fullScreen().strategy(new AdaptiveFullScreenStrategy(window));
This "window" - is awt.window

All rigth. But my application is javafx. And I have window only from javafx.  And there need AWT.
Help me please! Where I can to find information? How I can convert fx to awt?

Google carefully hides the answer to this question :(((

Can you to help me?

I will be grateful for any help!

Thank you!

Iliya Rudnitsky

**Comment by caprica** [comment]
For JavaFX, you just need to set the Stage to fullscreen, do not use the FullScreenApi provided by vlcj for this.

Here's the first random link I found to give you an idea: http://tutorials.jenkov.com/javafx/stage.html#stage-full-screen-mode
