### ISSUE TITLE
Problem running the code from jar file

### ISSUE THREAD

**Issue by burinc** [caprica/vlcj-player#23]
Hi @caprica

I am trying to run the project locally.
I can build the project without any issue but when trying to run it I got the following errors:

```shell
$java -jar target/vlcj-player-2.0.0-SNAPSHOT.jar 
Error: Could not find or load main class uk.co.caprica.vlcjplayer.VlcjPlayer
Caused by: java.lang.NoClassDefFoundError: uk/co/caprica/vlcj/player/renderer/RendererDiscovererEventListener
```

My system is Linux
Library used: vlcj-4.7.2-SNAPSHOT.jar  (build from source)

``` java -version
openjdk version "11.0.9" 2020-10-20 LTS
OpenJDK Runtime Environment Zulu11.43+21-CA (build 11.0.9+11-LTS)
OpenJDK 64-Bit Server VM Zulu11.43+21-CA (build 11.0.9+11-LTS, mixed mode)
```

I try also with  vlcj-4.4.2.jar and the same error as above.

Any idea/suggestion?

**Comment by caprica** [comment]
The manifest file in the jar contains a bunch of dependencies, and probably those dependent jar files are not in the same directory so it fails to find the necessary classes.

But this is a demo project, right, it's intended to be executed from an IDE or something anyway.

**Comment by burinc** [comment]
This can be closed as I can now run it from the CLI using the following method in this PR.

https://github.com/caprica/vlcj-player/compare/master...burinc:master
