### ISSUE TITLE
How do I set the desired subtitle track?

### ISSUE THREAD

**Issue by ilia-ru** [caprica/vlcj-player#25]
Hello!
How do I set the desired subtitle track?
I have been looking for an answer for several days, but without any result.
I looked in the documentation, searched the Internet, but alas.
This:
embeddedMediaPlayer.media().info().textTracks();
Gives me a list of tracks, but how do I turn on the right one?

Thank you in advance!
--
Ilya Rudnitsky

**Comment by caprica** [comment]
vlcj-5.x
embeddedMediaPlayer.tracks().selectTrack(track);

vlcj-4.x
embeddedMediaPlayer.subpictures().setTrack(trackId);

**Comment by ilia-ru** [comment]
Hello, Mark! Thank you very much! Immediately the world became brighter and more joyful :)))
