### ISSUE TITLE
Code usage request

### ISSUE THREAD

**Issue by xdsswar** [caprica/vlcj-player#27]
Hi, I would like to use some of  your code (https://github.com/caprica/vlcj-player) in a desktop app Im  creating to download and play videos from internet, I need to play the videos in a separated window and your code is perfect for that , but I need you approbation for that. Im not going to sell the app , Its just a personal project and Im planning to release it. And I will never forget to give you the credit. 
If its ok to let me use it , let me know pls. Thanks

**Comment by caprica** [comment]
I'm afraid not. Use the code under the license offered (GPL 3 or later) or write your own code from scratch.

**Comment by xdsswar** [comment]
Its ok, Thanks anyway.
