### ISSUE TITLE
Accessing the video buffer of vlcj

### ISSUE THREAD

**Issue by IswaryaH** [caprica/vlcj-player#5]
How do we access the current number of frames in the vlcj buffer and extract them. ie. Methods or links used for this.

**Comment by caprica** [comment]
I don't know what you mean.

**Comment by IswaryaH** [comment]
Can the vlcj buffer be accessed in java? What is the format of the data in the buffer? How can this data be retrieved? What are the methods to access it?

**Comment by caprica** [comment]
Have a look at the vlcj-javafx project, or the "direct" examples in the vlcj test sources.
