### ISSUE TITLE
It compiled but its not running

### ISSUE THREAD

**Issue by parthgupta95** [caprica/vlcj-player#7]
This is the error coming:

parth@parth-Inspiron-5521:~/Desktop/vlcj-player-1.0.0-SNAPSHOT$ java -jar vlcj-player-1.0.0-SNAPSHOT.jar
Exception in thread "main" java.lang.Error: Unresolved compilation problems: 
	NativeDiscovery cannot be resolved to a type
	The method run() of type new Runnable(){} must override a superclass method

	at uk.co.caprica.vlcjplayer.VlcjPlayer.main(VlcjPlayer.java:76)

**Comment by caprica** [comment]
Are you serious...
