### ISSUE TITLE
Transforme and transpose video

### ISSUE THREAD

**Issue by AbdelkarimTayache** [caprica/vlcj-player#8]
Hi, 
I'm implemented vlc player with clvj library, so i integrated an EmbedMediaplayer into a JPanel , i can control it easily without any problem, sometimes i have to load some video with specific dimension that gives a bad view, so i thought that i can transpose the video to get wide screen and best view, this is easy to do in real time with VLC Player but when i tried to do it in my application i can't find out, Please is there any suggestion that i can add to my code to be ready to transpose my videos in playing time without needs to create another vlcj application with another concept. 

best regards

**Comment by caprica** [comment]
There are API functions to control cropping, zoom and aspect ratio. Is that not enough?

Otherwise it's not clear to me what you're asking. 

And is this to do with the vlcj-player project specifically, or the vlcj library (if so you're in the wrong place)?

**Comment by AbdelkarimTayache** [comment]
let me first thank you for your fast respond, 

my purpose is to  transpose video, like this i can watch it without any problem, in fact, I'm using a phone camera that gives me a video with different orientation so, i want in some cases change the orientation of video or transpose it to see clearly some part of the video. you can see in this [thread ](http://stackoverflow.com/questions/26143159/vlcj-video-rotation) there is the explanation of what approximately i want to do, in VLC i can do it using video effect ( geometry effect: transformation) but i can't find out how to do it in a programming way. 
I already tried to change aspect ratio but it's just deforming the video. 
Now i'm using vlcj-player. if i want a solution with  vlcj library where can i ask ? 

Thank you

**Comment by caprica** [comment]
vlcj issues are here: https://github.com/caprica/vlcj/issues

I still don't understand fully what you mean by "transpose". You can crop, zoom and change aspect using the API that already exists. That's all you can do.

If you want to do something like the stackoverflow question that you linked, then the answer is in that thread - i.e. you find the native video filter that you want to use, and set the options on the media player factory. This does NOT work in real-time though.

There is no LibVLC API for those other video filters (like rotate).

**Comment by AbdelkarimTayache** [comment]
thank you i will check with the vlcj teams.
